name: Greetings

name: First interaction
on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
    - uses: actions/first-interaction@v1.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for your help in pointing it out :D'' first issue'
